// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"2021_03_30_0gz_Kleki","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Eli's_Book","status":true,"description":"v1.9 - Essential plugin for all Eli plugins.","parameters":{}},
{"name":"Eli_MapReveal","status":true,"description":"v1.6 - Cover and reveal a map as player walks!","parameters":{"regions":"1,2,3,4,5,6,7,8,9,10","image":"2021_03_30_0ha_Kleki","coverForm":"coverSquare","rangeId":"7","minRange":"0","visibility":"toggle","fadeSpeed":"1"}}
];
